from pydantic import BaseModel
from typing import List, Dict, Any

class FinalResponse(BaseModel):
    """
    Structured output generated by the Writer Agent.
    """
    task: str
    summary: str
    recommendations: List[Dict[str, Any]]
