from pydantic import BaseModel
from typing import List

class ResearchResult(BaseModel):
    """
    Represents the output of the Research Agent for a specific plan step.
    """
    step: str
    result: str

from schemas.final_response_schema import FinalResponse

from schemas.final_response_schema import FinalResponse

class WorkflowResponse(BaseModel):
    """
    The updated final API response scheme containing the initial task, 
    the plan generated by the PlannerAgent, historical memory context,
    the executed results from the ResearchAgent, and the final synthesized answer.
    """
    task: str
    plan: List[str]
    memory_context: List[str]
    research_results: List[ResearchResult]
    final_answer: FinalResponse
