import json
import re
from agents.base_agent import BaseAgent
from schemas.final_response_schema import FinalResponse

class CriticAgent(BaseAgent):
    """
    Agent responsible for reviewing the final answer generated by WriterAgent.
    It checks for completeness, coherence, and whether the answer addresses the original task.
    """
    
    def review_answer(self, task: str, answer: FinalResponse) -> dict:
        """
        Reviews the generated answer against the original task.
        Returns a dictionary with 'approved' (bool) and 'feedback' (str).
        """
        # Convert FinalResponse into a string for the prompt
        answer_text = json.dumps({
            "task": answer.task,
            "summary": answer.summary,
            "recommendations": answer.recommendations
        }, indent=2)
        
        prompt = f"""You are a strict, senior Critic Agent.

Your job is to review the final answer generated by the system.
Check if the answer is complete, avoids repetitions, and successfully addresses the original task.

Original Task: {task}

Proposed Final Answer:
{answer_text}

If the answer is excellent and requires no changes, approve it.
If the answer is lacking details, has errors, or is not well-structured, reject it and provide feedback on how to improve.

Return ONLY a JSON object in this exact format:
{{
  "approved": true or false,
  "feedback": "Detailed explanation of why it was approved or rejected and what needs fixing."
}}"""
        
        response_text = self.llm_provider.generate_response(prompt)
        
        try:
            # Clean and parse the output
            clean_text = response_text.strip()
            
            # Use regex to aggressively extract the JSON block
            json_match = re.search(r"\{.*\}", clean_text, re.DOTALL)
            if json_match:
                clean_text = json_match.group(0)
                
            data = json.loads(clean_text)
            
            return {
                "approved": bool(data.get("approved", False)),
                "feedback": str(data.get("feedback", "No feedback provided."))
            }
        except json.JSONDecodeError:
            # Fallback if evaluation parsing fails
            return {
                "approved": False,
                "feedback": f"Failed to parse Critic evaluation. Raw output: {response_text}"
            }
        except Exception as e:
            return {
                "approved": False,
                "feedback": f"Critic Agent error: {str(e)}"
            }
